---
- name: username
  pause:
    prompt: "Enter username:"
    echo: yes
  register: username
- name: Ensure group exists
  group:
    name: "{{ groupname.user_input | default('developers')}}"
    state: present
-   name: create user
    user: 
        name: "{{ username.user_input }}"
        shell: /bin/bash
        groups: "{{ groupname.user_input | default('developers')}}"
        append: yes
        create_home: yes
-   name: key
    pause:
        prompt: "Enter the key"
        echo: no
    register: keyvalue


- name: Set authorized key
  authorized_key:
    user: "{{ username.user_input }}"
    state: present
    key: "{{ keyvalue.user_input}}"


- meta: end_play
  when:
    option == "1"
- name: bulk condition
  include_role:
    name: useradd
  when:
    option == "2"
