---
-   hosts: localhost
    gather_facts: true
    become: true
    vars_prompt:
        - name: option
          prompt: "Enter the choise \n 1. useradd \n 2. Bulk user add \n 3. userdel \n 4. add group to sudoers \n"
          private: no
    roles:
        - { role: useradd, when: option == "1" or option == "useradd" }
        - { role: useradd, when: option == "2" or option == "useradd" }
        - { role: userdel, when: option== "3" or option == "userdel"}
        - { role: sudoers, when option == "4" or option == "add group to sudoers" or option  == "addgroup" }