---
- name: username
  pause:
    prompt: "Enter username:"
    echo: yes
  register: username

- name: Remove the user
  user:
    name: "{{ username.user_input}}"
    state: absent
    remove: yes
- meta: end_play
  when:
    option == "3"